# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: whoami
#   namespace: argocd
# spec:
#   destination:
#     namespace: whoami-example
#     server: 'https://kubernetes.default.svc'
#   project: default
#   source:
#     path: 'subcharts/whoami'
#     repoURL: 'https://github.com/lefterisALEX/k8s-examples.git'
#     targetRevision: HEAD
#     # helm:
#     #   valueFiles:
#     #   - values.yaml
#   syncPolicy:
#     automated:
#       prune: false
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: whoami-subchart
 namespace: -gitops
spec:
 destination:
   namespace: test
   server: https://kubernetes.default.svc
 project: default
 source:
   path: subcharts/whoami/
   repoURL: https://github.com/lefterisALEX/k8s-examples.git
   targetRevision: main
 sync:
   comparedTo:
     destination:
       namespace: test
       server: https://kubernetes.default.svc
     source:
       path: subcharts/whoami/
       repoURL: https://github.com/lefterisALEX/k8s-examples.git
       targetRevision: master
 syncPolicy:
   automated:
     prune: true
     selfHeal: true
   syncOptions:
   - CreateNamespace=true