apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: whoami-example
    server: 'https://kubernetes.default.svc'
  source:
    path: 'subcharts/whoami'
    repoURL: 'https://github.com/lefterisALEX/k8s-examples.git'
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
